namespace Nyarlathotep.Tests;

/// <summary>One control of a plan (event-library D31, walkable-spawns D9): the plan's slug and the D-item it belongs to
/// (its key, "walkable-spawns D2"), its name, and its failing, passing and empty cases. A test row names test methods of <see cref="Class"/> (`&lt;Name&gt;_fails_when_…`, `&lt;Name&gt;_passes_…`,
/// `&lt;Name&gt;_empty_…`); a cmd row names the script check or selftest in <see cref="Class"/> and its fixture paths
/// (under tools/) or selftest case names.</summary>
public sealed record ControlRow(string Control, string Name, string Kind, string Class, string[] Bad, string[] Good, string[] Empty,
    string Plan = ControlCases.EventLibrary)
{
    /// <summary>The row's key: plan slug and D-id.</summary>
    public string Key => $"{Plan} {Control}";
}

/// <summary>A control whose test or fixture a later Build-plan step builds (event-spawns D22, A15, A22, A29): it has no row
/// until that step, and fails once the step's post-audit is recorded or, for a step-4 control, once the csproj Version
/// is the plan's release.</summary>
public sealed record PendingControl(string Plan, string Control, int Step, string Release)
{
    public string Key => $"{Plan} {Control}";
}

/// <summary>The authoritative list of the plans' control cases (event-library D31, walkable-spawns D9), compared with
/// each listed plan's own D-items by ControlCaseTests.</summary>
public static class ControlCases
{
    public const string EventLibrary = "event-library";
    public const string WalkableSpawns = "walkable-spawns";
    public const string RaphaelApiAdmin = "raphael-api-admin";
    public const string Regions = "regions";
    public const string EventSpawns = "event-spawns";
    public const string Automation = "automation";
    public const string WaveSets = "wave-sets";

    /// <summary>The plans whose controls the table lists; each is copied to the test output under Resources/.</summary>
    public static readonly string[] Plans = [EventLibrary, WalkableSpawns, RaphaelApiAdmin, Regions, EventSpawns, Automation, WaveSets];

    /// <summary>The controls that have no row yet, each with the step that builds it (event-spawns D22).</summary>
    public static readonly IReadOnlyList<PendingControl> Pending =
    [
        new(WaveSets, "D23", 2, "0.9.0"),
        new(WaveSets, "D24", 3, "0.9.0"), new(WaveSets, "D25", 3, "0.9.0"), new(WaveSets, "D26", 3, "0.9.0"), new(WaveSets, "D27", 3, "0.9.0"),
    ];

    static ControlRow T(string control, string name, string cls, string[] bad, string[] good, string[] empty) =>
        new(control, name, "test", cls, bad.Select(x => $"{name}_fails_when_{x}").ToArray(), good.Select(x => $"{name}_passes_{x}").ToArray(),
            empty.Select(x => $"{name}_empty_{x}").ToArray());

    static ControlRow C(string control, string name, string check, string[] bad, string[] good, string[] empty) =>
        new(control, name, "cmd", check, bad, good, empty);

    /// <summary>The test classes the listed plans add (event-library's seven, walkable-spawns' two, raphael-api-admin's
    /// five, regions' EventAdminTests); every test method in them follows one of the three forms.</summary>
    public static readonly string[] NewClasses =
    [
        "TemplateLibraryTests", "TemplateCommandTests", "AuthoringTests", "AuthoringCapacityTests", "PillarSwitchTests",
        "ReadinessTests", "LibraryDependencyFailureTests", "SpawningTests", "HealthTests",
        "HumanReplyTests", "OutcomeCodeTests", "ApiTwinTests", "RateGateTests", "ApiOverloadTests", "EventAdminTests",
        "EndPathTests", "WavePrecedenceTests", "SpawnsDependencyFailureTests", "AutomationTests", "AutomationDependencyFailureTests", "SpawnPlacementTests",
        "WaveSetTests", "ScoreboardTests", "WaveSetDependencyFailureTests",
    ];

    /// <summary>The existing classes that gain the plans' cases; their earlier methods keep their names.</summary>
    public static readonly string[] ExistingClasses =
        ["CommandArgTests", "ConfigChangedTests", "AuthorizationTests", "ContractDocTests", "ControlPrecedenceTests", "DependencyFailureTests",
         "ApiLinesTests", "WireFormatTests", "PushTests", "PrivacyTests", "EventValidationTests", "SpawnLedgerTests"];

    public static readonly IReadOnlyList<ControlRow> Table =
    [
        T("D1", "TemplateCatalogue", "TemplateLibraryTests", ["template_breaks_a_rule", "file_is_broken"], ["real_file"], ["zero_templates"]),
        T("D2", "StarterTemplates", "TemplateLibraryTests", ["a_field_differs"], ["six_as_business_rules"], ["no_templates"]),
        T("D4", "TemplateList", "TemplateCommandTests", ["arguments_are_bad", "catalogue_unavailable", "info_id_unknown"],
            ["real_catalogue", "invalid_template_with_reason", "three_pages", "long_trigger_within_one_message"], ["catalogue"]),
        T("D5", "TemplateUse", "TemplateCommandTests", ["refused", "used_twice"], ["copy_disabled", "enabled_template_copied_disabled"], ["catalogue_unavailable"]),
        T("D6", "New", "AuthoringTests", ["refused"], ["skeleton"], ["events_file"]),
        T("D7", "Copy", "AuthoringTests", ["refused"], ["verbatim_disabled", "invalid_source_keeps_reason"], ["events_file"]),
        T("D8", "DeleteArming", "AuthoringTests", ["confirm_not_armed", "running", "deleted_by_another_admin"], ["confirm_within_30s"], ["no_pending_delete"]),
        T("D9", "TriggerFields", "AuthoringTests", ["value_is_bad", "duplicate_day", "duplicate_time", "duplicate_boss", "other_trigger_type"],
            ["each_type"], ["value"]),
        T("D9", "TriggerFields", "CommandArgTests", ["characters_are_bad"], ["well_formed"], ["list_entry"]),
        T("D10", "ActionFields", "AuthoringTests", ["value_is_bad", "duplicate_unit", "duplicate_faction"],
            ["factions_and_units", "unknown_name_disabled_by_reload"], ["value"]),
        T("D10", "ActionFields", "CommandArgTests", ["name_breaks_rule"], ["96_character_name"], ["list_entry"]),
        T("D11", "Location", "AuthoringTests", ["refused"], ["point_rounded"], ["no_character"]),
        T("D12", "Equivalence", "AuthoringTests", ["file_changed_on_disk", "stale_file_alters_the_plan", "newer_schema", "over_1_mb"],
            ["write_equals_hand_edit", "two_admin_sequential_set", "running_instance_keeps_end_time"], ["refused_plan"]),
        T("D12", "Equivalence", "ConfigChangedTests", ["write_refused"], ["one_notice_per_applied_write"], ["events_file"]),
        T("D13", "PillarMap", "PillarSwitchTests", ["map_and_keys_differ"], ["settings_keys"], ["settings_text"]),
        T("D14", "PillarCommand", "PillarSwitchTests", ["off_processed_before_start", "no_change", "hand_edit_already_set_it", "reload_throws"],
            ["list", "switch_on_and_off", "reload_keeps_hand_edit", "ordering_start_before_off", "off_after_hand_edit_ends_running"], ["nothing_running"]),
        T("D16", "Readiness", "ReadinessTests", ["blocker_has_no_label", "a_control_blocks"],
            ["every_combination", "combination_count", "labels_one_to_one", "list_master_line_and_running"], ["no_events"]),
        T("D16", "Readiness", "ControlPrecedenceTests", ["blocker_unlabelled"], ["same_cause_as_start_refusal"], ["open_controls"]),
        T("D17", "LibraryKinds", "AuthorizationTests", ["not_admin"], ["admin_only"], ["work_reply"]),
        C("D17", "VcfDependency", "preflight -AuthSuite › Test-CheckVcfDependency",
            ["selftest VcfDependency/bad", "selftest VcfDependency/bad-2", "selftest VcfDependency/bad-3"], ["selftest VcfDependency/good"], ["selftest VcfDependency/empty"]),
        C("D18", "CfgWrites", "preflight -SelfTest › Test-CheckCfgWrites",
            ["selftest CfgWrites/bad", "selftest CfgWrites/bad-2", "selftest TemplatesJson/bad-3"], ["selftest CfgWrites/good"], ["selftest CfgWrites/empty"]),
        T("D19", "SaveFailure", "PillarSwitchTests", ["save_truncates_then_throws", "file_lacks_or_garbles_key"], ["line_written_then_throws", "off_ends_events_when_file_says_off", "file_values_read"], ["file_after_truncate"]),
        T("D19", "EventsWrite", "LibraryDependencyFailureTests", ["tmp_write_fails"], ["after_disk_recovers"], ["refused_plan_writes_nothing"]),
        T("D19", "EventsPromote", "LibraryDependencyFailureTests", ["promote_replaces_then_throws"], ["throw_before_replace_keeps_file"], ["events_file"]),
        T("D19", "StateWrite", "LibraryDependencyFailureTests", ["state_write_fails", "state_read_only"], ["both_writes"], ["no_cooldown_row", "null_cooldown_rows"]),
        T("D19", "Catalogue", "LibraryDependencyFailureTests", ["missing_or_unparsable"], ["real_file"], ["zero_templates"]),
        T("D19", "LocationContext", "LibraryDependencyFailureTests", ["no_character"], ["character_in_world"], ["console_context"]),
        T("D19", "PhaseSource", "LibraryDependencyFailureTests", ["read_throws"], ["edges"], ["no_phase_hook"]),
        T("D20", "SettableFields", "CommandArgTests", ["name_outside_table"], ["every_table_name"], ["field_name"]),
        T("D20", "CommandForms", "CommandArgTests", ["form_is_malformed"], ["each_declared_form"], ["arguments"]),
        T("D20", "DesignDoc", "ContractDocTests", ["table_differs"], ["forms_and_fields_match"], ["section"]),
        C("D24", "SoakReport", "soak-report.ps1 -SelfTest",
            ["selftest bad-unpaired", "selftest bad-tick", "selftest bad-unhandled", "selftest bad-short", "selftest bad-missing-template"],
            ["selftest good"], ["selftest empty"]),
        T("D27", "Capacity", "AuthoringCapacityTests", ["file_holds_200"],
            ["creating_form_writes_200th", "set_and_delete_at_200", "each_write_under_200ms_at_199", "near_1mb_set_and_delete_under_200ms"], ["events_file"]),
        C("D28", "ReleaseVerify", "release-verify.ps1 -SelfTest",
            ["selftest missing asset", "selftest differing hash"], ["selftest matching hash"], ["selftest no audit records the asset"]),
        C("D29", "RollbackRoutes", "preflight -RollbackOf › RollbackRoutes",
            ["selftest RollbackRoutes/bad", "selftest RollbackRoutes/bad-2", "selftest RollbackRoutes/bad-3"], ["selftest RollbackRoutes/good"], ["selftest RollbackRoutes/empty"]),
        C("D30", "DataInventory", "preflight -SelfTest › data inventory and -Paths -DeclaredOf",
            ["selftest DataInventory/bad-el", "selftest DataInventory/bad-tmp", "selftest DataInventory/bad-tmp-2", "selftest Paths/bad-undeclared", "selftest Paths/bad-soak"],
            ["selftest DataInventory/good"], ["selftest DataInventory/empty"]),
        T("D31", "ControlCases", "ControlCaseTests", ["table_breaks_a_rule", "pending_key_has_a_row", "pending_key_is_no_control", "pending_after_its_post_audit",
            "audit_missing", "pending_at_release"], ["plan_and_table_agree"], ["plan_without_controls"]),
        T("D32", "Degraded", "LibraryDependencyFailureTests", ["write_uncertain"], ["cleared_by_clean_write_or_reload"], ["healthy"]),
        C("D33", "DependencySuite", "preflight -DependencySuite",
            ["selftest DependencySuite/bad", "selftest DependencySuite/bad-2", "selftest DependencySuite/bad-floor-spawns"], ["selftest DependencySuite/good"], ["selftest DependencySuite/empty"]),
        C("D34", "TestRuns", "preflight Invoke-ClassTests",
            ["selftest TestRuns/bad", "selftest TestRuns/bad-2", "selftest TestRuns/bad-3"], ["selftest TestRuns/good"], ["selftest TestRuns/empty"]),
        T("D36", "SlowTick", "EngineTests", ["tick_reaches_250ms", "ticks_repeat_within_a_minute"], ["ticks_under_250ms"], ["no_phase_timings"]),

        // ---- walkable-spawns (D9): a cmd row names the fixtures under tools/ that fail and pass it
        T("D2", "SpawnPoints", "SpawningTests", ["all_blocked", "blocked_point_kept"],
            ["free_ring_point_kept", "search_order", "first_free_in_order", "centre_when_only_centre_free"], ["radius_zero"]) with { Plan = WalkableSpawns },
        T("D3", "WavePoints", "SpawningTests", ["not_grounded", "budget_spent", "budget_spent_mid_search", "check_throws", "point_is_nan"],
            ["one_point_per_unit_in_order", "blocked_ring_point_moved", "counts_match_kinds"], ["no_probe"]) with { Plan = WalkableSpawns },
        T("D5", "WalkCheck", "DependencyFailureTests",
            ["check_throws", "streak_repeats", "unanswered_wave_closes_streak", "tile_world_missing", "height_out_of_range"],
            ["recovered_check_used_again", "height_in_range"], ["no_height"]) with { Plan = WalkableSpawns },
        T("D6", "WalkHealth", "HealthTests", ["streak_open"], ["recovered_check_clears_entry"], ["healthy"]) with { Plan = WalkableSpawns },
        T("D7", "WalkRadius", "CommandArgTests", ["refused"], ["in_range"], ["absent"]) with { Plan = WalkableSpawns },
        C("D9", "DebugCommands", "preflight › Test-CheckDebugCommands",
            ["tools/preflight-fixtures/DebugCommands/bad", "tools/preflight-fixtures/DebugCommands/bad-2", "tools/preflight-fixtures/DebugCommands/bad-3",
             "tools/preflight-fixtures/DebugCommands/bad-4", "tools/preflight-fixtures/DebugCommands/bad-5", "tools/preflight-fixtures/DebugCommands/bad-6",
             "tools/preflight-fixtures/DebugCommands/bad-7", "tools/preflight-fixtures/DebugCommands/bad-8"],
            ["tools/preflight-fixtures/DebugCommands/good"], ["tools/preflight-fixtures/DebugCommands/empty"]) with { Plan = WalkableSpawns },
        C("D10", "ProbeRecords", "preflight -SessionsOf › Test-CheckSessionLogs",
            ["tools/preflight-fixtures/SessionLogs/bad-probe", "tools/preflight-fixtures/SessionLogs/bad-probe-2", "tools/preflight-fixtures/SessionLogs/bad-probe-3",
             "tools/preflight-fixtures/SessionLogs/bad-probe-4", "tools/preflight-fixtures/SessionLogs/bad-probe-5", "tools/preflight-fixtures/SessionLogs/bad-probe-6"],
            ["tools/preflight-fixtures/SessionLogs/good"], ["tools/preflight-fixtures/SessionLogs/empty"]) with { Plan = WalkableSpawns },
        C("D11", "Secrets", "preflight › Test-CheckSecrets",
            ["tools/preflight-fixtures/Secrets/bad", "tools/preflight-fixtures/Secrets/bad-9"],
            ["tools/preflight-fixtures/Secrets/good"], ["tools/preflight-fixtures/Secrets/empty"]) with { Plan = WalkableSpawns },
        C("D12", "KnownIssue", "preflight › Test-CheckChangelogs",
            ["tools/preflight-fixtures/Changelogs/bad-knownissue", "tools/preflight-fixtures/Changelogs/bad-knownissue-2"], ["tools/preflight-fixtures/Changelogs/good"],
            ["tools/preflight-fixtures/Changelogs/empty"]) with { Plan = WalkableSpawns },
        // ---- raphael-api-admin (D11): a cmd row names the fixtures under tools/ that fail and pass it
        T("D1", "HumanReply", "HumanReplyTests", ["reply_differs"], ["captured_rows", "every_row_has_a_scenario", "newest_capture_wins"], ["capture"])
            with { Plan = RaphaelApiAdmin },
        C("D1", "HumanReplies", "preflight › Test-CheckHumanReplies and Test-CheckOutcomeReturns",
            ["tools/preflight-fixtures/HumanReplies/bad", "tools/preflight-fixtures/HumanReplies/bad-2", "tools/preflight-fixtures/HumanReplies/bad-3", "tools/preflight-fixtures/HumanReplies/bad-4", "tools/preflight-fixtures/HumanReplies/bad-5", "tools/preflight-fixtures/OutcomeReturns/bad", "tools/preflight-fixtures/OutcomeReturns/bad-2", "tools/preflight-fixtures/OutcomeReturns/bad-3"],
            ["tools/preflight-fixtures/HumanReplies/good", "tools/preflight-fixtures/OutcomeReturns/good"], ["tools/preflight-fixtures/HumanReplies/empty", "tools/preflight-fixtures/OutcomeReturns/empty"])
            with { Plan = RaphaelApiAdmin },
        T("D2", "OutcomeCode", "OutcomeCodeTests", ["cell_changes", "a_code_has_no_twin", "built_outside_factories"],
            ["each_refusal_row", "every_row_has_a_case", "codes_map_one_to_one", "reasons_closed_list"], ["plan_table"]) with { Plan = RaphaelApiAdmin },
        T("D3", "Event", "ApiTwinTests", ["verb_unknown", "argument_bad", "human_badarg_would_log", "refused"],
            ["each_verb_ok_line", "gateway_kind_before_op", "log_line_prefixed", "one_grammar_line_each"], ["arguments"]) with { Plan = RaphaelApiAdmin },
        T("D4", "TemplatePillarPurge", "ApiTwinTests", ["argument_bad", "pillar_save_fails", "purge_confirm_lacks_cooldown"], ["ok_lines"], ["nothing_to_purge"])
            with { Plan = RaphaelApiAdmin },
        T("D5", "Idempotency", "ApiTwinTests", ["start_or_stop_repeats", "confirm_is_not_the_askers"],
            ["held_enable_writes_nothing", "held_pillar_writes_nothing", "held_off_ends_running", "set_to_held_value_writes", "human_ask_twin_confirm",
             "two_admins_confirm_in_one_second"], ["confirm_without_ask"]) with { Plan = RaphaelApiAdmin },
        T("D6", "RateGate", "RateGateTests", ["sixth_within_a_second", "gate_full_of_active_admins"],
            ["five_in_a_second", "sliding_window", "admins_apart", "idle_admins_pruned", "clock_stepped_back"], ["no_prior_twins"]) with { Plan = RaphaelApiAdmin },
        T("D6", "RateOrder", "ApiTwinTests", ["sixth_twin_runs"], ["reads_and_human_not_counted", "one_second_later_and_per_admin"], ["first_twin"])
            with { Plan = RaphaelApiAdmin },
        T("D7", "AdminReads", "ApiLinesTests", ["cooldown_is_over", "catalogue_unavailable", "filter_or_page_is_bad"],
            ["templates_rows", "template_info", "pillar_list_in_order", "killswitch_during_cooldown", "through_the_flows"], ["no_templates_no_events"])
            with { Plan = RaphaelApiAdmin },
        T("D8", "AdminTwins", "WireFormatTests", ["key_order_differs", "forbidden_character_given"], ["contract_examples", "longest_values_cut"], ["value"])
            with { Plan = RaphaelApiAdmin },
        T("D9", "Twins", "ConfigChangedTests", ["refused_or_unchanged"], ["same_pushes_as_human", "changed_pillar_one_notice"], ["reads_queue_nothing"])
            with { Plan = RaphaelApiAdmin },
        T("D9", "Twins", "PushTests", ["refused"], ["start_stop_purge_as_human", "pillar_off_ends_running"], ["nothing_to_purge"]) with { Plan = RaphaelApiAdmin },
        T("D10", "ContractApi4", "ContractDocTests", ["contract_regresses", "handoff_or_design_lags"], ["contract_handoff_and_design"], ["contract"])
            with { Plan = RaphaelApiAdmin },
        C("D10", "WireContract", "preflight › Test-CheckWireContract", ["tools/preflight-fixtures/WireContract/bad", "tools/preflight-fixtures/WireContract/bad-2", "tools/preflight-fixtures/WireContract/bad-3", "tools/preflight-fixtures/WireContract/bad-9"],
            ["tools/preflight-fixtures/WireContract/good"], ["tools/preflight-fixtures/WireContract/empty"]) with { Plan = RaphaelApiAdmin },
        T("D11", "ApiOverload", "ApiOverloadTests", ["two_commands_share_a_count"], ["real_table"], ["table"]) with { Plan = RaphaelApiAdmin },
        T("D11", "ControlCases", "ControlCaseTests", ["table_breaks_a_rule"], ["plan_and_table_agree"], ["plan_without_controls"]) with { Plan = RaphaelApiAdmin },
        C("D11", "AdminStatic", "preflight -AuthSuite › Test-CheckCommands, Test-CheckGatewayOnly and Test-CheckWireContract",
            ["tools/preflight-fixtures/Commands/bad-2", "tools/preflight-fixtures/Commands/bad-3", "tools/preflight-fixtures/Commands/bad-4", "tools/preflight-fixtures/GatewayOnly/bad-6", "tools/preflight-fixtures/GatewayOnly/bad-7", "tools/preflight-fixtures/GatewayOnly/bad-8", "tools/preflight-fixtures/WireContract/bad-10", "tools/preflight-fixtures/WireContract/bad-11",
             "tools/preflight-fixtures/WireContract/bad-12", "tools/preflight-fixtures/WireContract/bad-13"],
            ["tools/preflight-fixtures/Commands/good", "tools/preflight-fixtures/GatewayOnly/good", "tools/preflight-fixtures/WireContract/good"],
            ["tools/preflight-fixtures/Commands/empty", "tools/preflight-fixtures/GatewayOnly/empty", "tools/preflight-fixtures/WireContract/empty"]) with { Plan = RaphaelApiAdmin },
        T("D12", "Twin", "DependencyFailureTests", ["op_throws", "other_twin_op_throws", "streak_repeats", "save_fails"],
            ["throw_after_clean_run_logged_again", "memory_equals_file_after_refused_write", "throw_after_change_is_internal"], ["clean_run_warns_nothing"]) with { Plan = RaphaelApiAdmin },
        C("D14", "Records", "preflight -AuditOf, -SessionsOf and -Paths -DeclaredOf › AuditSteps, SessionLogs, Paths and DataInventory",
            ["tools/preflight-fixtures/AuditSteps/bad", "tools/preflight-fixtures/AuditSteps/bad-2", "tools/preflight-fixtures/SessionLogs/bad", "tools/preflight-fixtures/SessionLogs/bad-2", "tools/preflight-fixtures/Paths/bad-undeclared", "tools/preflight-fixtures/Paths/bad-temp", "tools/preflight-fixtures/DataInventory/bad", "tools/preflight-fixtures/DataInventory/bad-2"],
            ["tools/preflight-fixtures/AuditSteps/good", "tools/preflight-fixtures/SessionLogs/good", "tools/preflight-fixtures/Paths/good", "tools/preflight-fixtures/DataInventory/good"],
            ["tools/preflight-fixtures/AuditSteps/empty", "tools/preflight-fixtures/SessionLogs/empty", "tools/preflight-fixtures/Paths/empty", "tools/preflight-fixtures/DataInventory/empty"]) with { Plan = RaphaelApiAdmin },
        C("D15", "Secrets", "preflight › Test-CheckSecrets", ["tools/preflight-fixtures/Secrets/bad", "tools/preflight-fixtures/Secrets/bad-9"], ["tools/preflight-fixtures/Secrets/good"],
            ["tools/preflight-fixtures/Secrets/empty"]) with { Plan = RaphaelApiAdmin },
        T("D15", "Twins", "PrivacyTests", ["a_line_carries_the_id"], ["no_id_name_or_position", "location_here_value_only"], ["no_events"]) with { Plan = RaphaelApiAdmin },
        C("D16", "Release", "preflight › Test-CheckVersion; -RollbackOf › RollbackRoutes; release-verify.ps1 -SelfTest",
            ["tools/preflight-fixtures/Version/bad", "tools/preflight-fixtures/RollbackRoutes/bad", "tools/preflight-fixtures/RollbackRoutes/bad-2", "tools/preflight-fixtures/RollbackRoutes/bad-3", "selftest missing asset", "selftest differing hash"],
            ["tools/preflight-fixtures/Version/good", "tools/preflight-fixtures/RollbackRoutes/good", "selftest matching hash"],
            ["tools/preflight-fixtures/Version/empty", "tools/preflight-fixtures/RollbackRoutes/empty", "selftest no audit records the asset"]) with { Plan = RaphaelApiAdmin },
        // ---- regions (D11): the test rows name the form-named cases; a cmd row names the fixtures under tools/
        T("D1", "Point", "RegionTests", ["not_finite", "polygon_degenerate_or_untagged"], ["each_shape", "first_polygon_in_index_order"], ["index"])
            with { Plan = Regions },
        C("D2", "RegionsLine", "preflight -LogCheck › Test-CheckLogCheck",
            ["tools/preflight-fixtures/LogCheck/bad-regions-missing", "tools/preflight-fixtures/LogCheck/bad-regions-zero",
             "tools/preflight-fixtures/LogCheck/bad-regions-differ", "tools/preflight-fixtures/LogCheck/bad-regions-noversion"],
            ["tools/preflight-fixtures/LogCheck/good-regions", "tools/preflight-fixtures/LogCheck/good-regions-restart"], ["tools/preflight-fixtures/LogCheck/empty"]) with { Plan = Regions },
        T("D3", "Scope", "EventValidationTests", ["invalid", "name_not_on_map"],
            ["every_trigger_type", "trigger_and_action_independent", "case_insensitive_names_in_games_spelling"], ["absent_is_global"]) with { Plan = Regions },
        T("D4", "Region", "TriggerActivationTests", ["kill_position_unreadable"], ["kill_inside_regions", "schedule_due_once"], ["global_trigger", "global_kill_reads_no_position"])
            with { Plan = Regions },
        T("D4", "ScopeGate", "EngineTests", ["no_reader_or_lookup", "kill_outside_scope", "admin_start_without_player_inside", "position_source_throws"],
            ["player_in_regions", "in_region_kill_without_player", "skip_line_only_for_system_starts"], ["global_trigger"]) with { Plan = Regions },
        T("D4", "RegionRefusal", "OutcomeCodeTests", ["outside_or_no_player"], ["player_inside"], ["no_players"]) with { Plan = Regions },
        T("D5", "Region", "EmpowerEligibilityTests", ["position_unreadable"],
            ["in_region_applied_out_of_region_skipped", "skip_order", "carried_unit_keeps_carrier"], ["global_scope"]) with { Plan = Regions },
        T("D6", "RegionWaves", "SpawningTests",
            ["out_of_scope_point_used", "scope_spends_budget", "budget_spent_keeps_outside_ring_point", "fall_open_places_outside_ring_point"],
            ["in_scope_placement"], ["global_no_scope_call"]) with { Plan = Regions },
        T("D7", "Regions", "DependencyFailureTests", ["no_polygons", "build_throws", "log_sink_throws", "names_differ"],
            ["unavailable_wins_over_not_on_map", "reload_rebuilds_and_clears_health", "built_before_definitions", "read_only_map"],
            ["healthy_build_leaves_no_health_entry"]) with { Plan = Regions },
        T("D8", "Lines", "RegionTests", ["definition_disabled", "here_position_unreadable"], ["list_counts_per_region_then_global", "here_region_outside_or_unavailable"], ["no_events"])
            with { Plan = Regions },
        T("D9", "Scope", "EventAdminTests", ["set_value_reload_rejects", "set_more_names_than_regions", "trigger_type_changes"],
            ["info_shows_both_scopes", "list_suffix_regional_only", "set_writes_games_spelling", "set_every_trigger_type", "edit_leaves_running_instance"],
            ["value"]) with { Plan = Regions },
        T("D10", "Region", "ApiLinesTests", ["longest_values_with_ten_regions"],
            ["rows_carry_action_scope", "pushes_on_start_and_end_only", "read_counts_in_game_order"], ["no_active_events"]) with { Plan = Regions },
        C("D10", "WireContract", "preflight › Test-CheckWireContract", ["tools/preflight-fixtures/WireContract/bad", "tools/preflight-fixtures/WireContract/bad-2", "tools/preflight-fixtures/WireContract/bad-3", "tools/preflight-fixtures/WireContract/bad-9"],
            ["tools/preflight-fixtures/WireContract/good"], ["tools/preflight-fixtures/WireContract/empty"]) with { Plan = Regions },
        T("D11", "ControlCases", "ControlCaseTests", ["table_breaks_a_rule"], ["plan_and_table_agree"], ["plan_without_controls"]) with { Plan = Regions },
        C("D11", "RegionCommand", "preflight -AuthSuite › Test-CheckCommands", ["tools/preflight-fixtures/Commands/bad-13"],
            ["tools/preflight-fixtures/Commands/good"], ["tools/preflight-fixtures/Commands/empty"]) with { Plan = Regions },
        C("D13", "Records", "preflight -AuditOf, -SessionsOf and -Paths -DeclaredOf › AuditSteps, SessionLogs, Paths and DataInventory",
            ["tools/preflight-fixtures/AuditSteps/bad", "tools/preflight-fixtures/AuditSteps/bad-2", "tools/preflight-fixtures/SessionLogs/bad", "tools/preflight-fixtures/SessionLogs/bad-2", "tools/preflight-fixtures/Paths/bad-undeclared", "tools/preflight-fixtures/Paths/bad-temp", "tools/preflight-fixtures/DataInventory/bad", "tools/preflight-fixtures/DataInventory/bad-2"],
            ["tools/preflight-fixtures/AuditSteps/good", "tools/preflight-fixtures/SessionLogs/good", "tools/preflight-fixtures/Paths/good", "tools/preflight-fixtures/DataInventory/good"],
            ["tools/preflight-fixtures/AuditSteps/empty", "tools/preflight-fixtures/SessionLogs/empty", "tools/preflight-fixtures/Paths/empty", "tools/preflight-fixtures/DataInventory/empty"]) with { Plan = Regions },
        C("D14", "Secrets", "preflight › Test-CheckSecrets", ["tools/preflight-fixtures/Secrets/bad", "tools/preflight-fixtures/Secrets/bad-9"], ["tools/preflight-fixtures/Secrets/good"],
            ["tools/preflight-fixtures/Secrets/empty"]) with { Plan = Regions },
        T("D14", "Region", "PrivacyTests", ["a_line_carries_the_position"], ["no_position_name_or_id"], ["global_event"]) with { Plan = Regions },
        T("D15", "Cost", "RegionTests", ["fixture_missing_or_zero"], ["10000_points_over_a_real_sized_index", "a_sweep_reads_one_position_per_unit"],
            ["global_scope_reads_no_position"]) with { Plan = Regions },
        C("D16", "Release", "preflight › Test-CheckVersion; -RollbackOf › RollbackRoutes; release-verify.ps1 -SelfTest",
            ["tools/preflight-fixtures/Version/bad", "tools/preflight-fixtures/RollbackRoutes/bad", "tools/preflight-fixtures/RollbackRoutes/bad-2", "tools/preflight-fixtures/RollbackRoutes/bad-3", "selftest missing asset", "selftest differing hash"],
            ["tools/preflight-fixtures/Version/good", "tools/preflight-fixtures/RollbackRoutes/good", "selftest matching hash"],
            ["tools/preflight-fixtures/Version/empty", "tools/preflight-fixtures/RollbackRoutes/empty", "selftest no audit records the asset"]) with { Plan = Regions },
        // ---- event-spawns (D22): D19, D24 and D25 are pending (D21 joined in step 2); the cmd rows join with their preflight fixtures
        T("D6", "Spawns", "EventValidationTests",
            ["key_out_of_range", "unknown_key"], ["every_new_key", "every_trigger_takes_aroundplayer", "definition_without_new_keys_unchanged"],
            ["modifiers_object"]) with { Plan = EventSpawns },
        T("D8", "WaveRoll", "SpawningTests",
            ["chance_one_loses_a_copy", "copies_rolled_as_one", "order_changes", "caps_clamp_pre_roll_count", "zero_roll_spawns_or_throws"],
            ["independent_copies_in_entry_order"], ["unit_list"]) with { Plan = EventSpawns },
        T("D9", "Tuning", "SpawningTests",
            ["stat_maps_to_another", "value_not_multiplier_minus_one", "power_or_attack_speed_not_two_entries", "one_gives_an_entry", "level_delta_not_from_prefab_level"],
            ["every_modifier", "spawn_command_same_function"], ["no_modifiers"]) with { Plan = EventSpawns },
        T("D11", "Loot", "SpawningTests", ["order_without_loot_keeps_drops", "loot_order_clears_drops"], ["each_order_carries_its_flag"], ["order_without_loot"])
            with { Plan = EventSpawns },
        T("D13", "Hunt", "SpawningTests",
            ["ineligible_player_targeted", "tally_counts_a_player_twice", "sixth_target_added", "order_not_by_distance", "duplicate_planned", "player_in_buffer_seeded",
             "plan_for_ended_wave", "stale_seed_kept", "game_entry_removed", "empty_targets_keep_a_seed", "race_leaves_record_buffer_lacks",
             "replaced_entry_removed", "rewritten_seed_left_to_the_game", "buffer_read_hides_a_shared_player", "removal_takes_a_shared_or_other_entry", "tick_reads_other_map", "seeds_while_latest_build_failed"],
            ["tick_seeds_and_keeps", "tally_counts_each_player_once"], ["no_players"]) with { Plan = EventSpawns },
        T("D16", "PlayerPick", "SpawningTests",
            ["ineligible_player_picked", "distance_leaves_range", "pick_not_uniform", "queued_centre_changes", "out_of_scope_player_picked",
             "out_of_scope_centre_used", "throwing_read_spawns", "claimed_first_angle_moves_centre"],
            ["eligible_player_centre"], ["no_players"]) with { Plan = EventSpawns },
        T("D16", "PlayerPick", "PrivacyTests", ["a_line_names_the_player"], ["no_line_names_or_locates_the_player"], ["no_players"]) with { Plan = EventSpawns },
        T("D17", "Territory", "SpawningTests",
            ["block_conversion_differs", "listed_block_point_free", "outside_point_claimed", "out_of_range_block_kept", "allow_territory_wave_refused",
             "failed_map_spawns_wave_that_needs_it"],
            ["castle_blocks_claimed"], ["block_set"]) with { Plan = EventSpawns },
        T("D18", "Spawns", "AuthoringTests", ["value_refused", "second_level_form", "empower_definition", "refusal_names_wrong_argument"], ["valid_set_changes_file"], ["value"])
            with { Plan = EventSpawns },
        T("D18", "Spawns", "CommandArgTests", ["value_out_of_range", "field_not_settable"], ["values_in_range"], ["value"]) with { Plan = EventSpawns },
        T("D21", "Territory", "SpawnsDependencyFailureTests",
            ["out_of_range_block_kept", "failed_build_spawns_a_wave_that_needs_it", "failed_build_keeps_hunting"],
            ["rebuilt_map_clears_territory_unknown"], ["no_castle_hearts"]) with { Plan = EventSpawns },
        T("D21", "HuntSeed", "SpawnsDependencyFailureTests",
            ["failure_ends_the_wave_or_repeats_its_line", "partial_write_leaves_a_record_the_buffer_lacks"],
            ["recovered_seeding_clears_entry"], ["no_hunt_units"]) with { Plan = EventSpawns },
        T("D21", "PlayerQuery", "SpawnsDependencyFailureTests", ["nan_position_is_picked", "failed_query_or_region_read_spawns"],
            ["readable_player_is_picked"], ["no_players"]) with { Plan = EventSpawns },
        T("D21", "UnitRecipe", "SpawnsDependencyFailureTests", ["failing_unit_untracks_the_others_or_stays_tracked"],
            ["every_recipe_applies"], ["zero_units_requested"]) with { Plan = EventSpawns },
        T("D20", "Spawns", "PushTests", ["skipped_wave_pushes", "skipped_wave_pushes_or_is_retried", "row_carries_a_new_field"], ["api_5_and_rows_unchanged"], ["definition_without_new_keys"])
            with { Plan = EventSpawns },
        T("D29", "WavePrecedence", "WavePrecedenceTests",
            ["blocked_reaches_roll", "player_skip_before_territory_unknown", "claimed_before_player_skip", "claimed_before_query_failed",
             "roll_before_claimed", "caps_before_zero_roll", "allow_territory_lifts_a_cap", "allow_territory_lifts_player_skip",
             "allow_territory_lifts_unknown_on_aroundplayer", "allow_territory_lifts_unknown_on_hunt", "point_with_allow_territory_and_failed_map_skipped",
             "skipped_wave_rolls"],
            ["stated_order", "allow_territory_lifts_only_territory_skip"], ["nothing_blocked_roll_zero"]) with { Plan = EventSpawns },
        T("D30", "Spawns", "HealthTests", ["streak_open", "ended_event_keeps_territory_unknown"], ["recovered_check_clears_entry", "text_equals_table"], ["no_open_streak"])
            with { Plan = EventSpawns },
        T("D19", "StarterTemplates", "TemplateLibraryTests", ["spawn_modifiers_differ", "a_spawn_template_is_enabled_or_invalid"],
            ["six_as_business_rules"], ["no_templates"]) with { Plan = EventSpawns },
        C("D24", "TimingSpan", "preflight -TimingSpan › Test-CheckTimingSpan",
            ["tools/preflight-fixtures/TimingSpan/bad", "tools/preflight-fixtures/TimingSpan/bad-avg", "tools/preflight-fixtures/TimingSpan/bad-slow",
             "tools/preflight-fixtures/TimingSpan/bad-gap", "tools/preflight-fixtures/TimingSpan/bad-notarget", "tools/preflight-fixtures/TimingSpan/bad-tracked",
             "tools/preflight-fixtures/TimingSpan/bad-slowlast"],
            ["tools/preflight-fixtures/TimingSpan/good"], ["tools/preflight-fixtures/TimingSpan/empty"]) with { Plan = EventSpawns },
        T("D24", "TickTimer", "EngineTests", ["slowest_names_another_tick"], ["top_three_phases_of_the_slowest_tick"], ["window_without_phases"]) with { Plan = EventSpawns },
        T("D32", "ChatBytes", "CommandArgTests", ["line_exceeds_480", "line_holds_markup", "usage_holds_markup"], ["new_lines_at_maximum_lengths"], ["fields"]) with { Plan = EventSpawns },
        T("D33", "EndPaths", "EndPathTests",
            ["natural_end_leaves_state", "event_stop_leaves_state", "fault_cancel_leaves_state", "purge_leaves_state", "purge_leaves_a_streak_open", "event_end_leaves_its_streaks", "runtime_skips_a_streak_close", "restart_keeps_state",
             "stopping_one_touches_the_other"],
            ["every_path_empties_all_three"], ["event_without_units"]) with { Plan = EventSpawns },
        C("D22", "Authorization", "preflight -AuthSuite (the real tree) and -SelfTest (these fixture batteries) › Test-CheckGatewayOnly, Test-CheckMutatingFloor and Test-CheckAuthSuite",
            ["tools/preflight-fixtures/AuthSuite/bad-inherited", "tools/preflight-fixtures/AuthSuite/bad-unhandled", "tools/preflight-fixtures/AuthSuite/bad-literal", "tools/preflight-fixtures/AuthSuite/bad-gutted", "tools/preflight-fixtures/GatewayOnly/bad-tickcaller", "tools/preflight-fixtures/GatewayOnly/bad-new",
             "tools/preflight-fixtures/GatewayOnly/bad-rootcaller", "tools/preflight-fixtures/GatewayOnly/bad-instance", "tools/preflight-fixtures/GatewayOnly/bad-samename",
             "tools/preflight-fixtures/GatewayOnly/bad-systemcaller", "tools/preflight-fixtures/GatewayOnly/bad-systemtype", "tools/preflight-fixtures/GatewayOnly/bad-alias", "tools/preflight-fixtures/GatewayOnly/bad-shadow", "tools/preflight-fixtures/GatewayOnly/bad-tuple",
             "tools/preflight-fixtures/MutatingFloor/bad", "tools/preflight-fixtures/MutatingFloor/bad-tuple", "tools/preflight-fixtures/MutatingFloor/bad-renamed",
             "tools/preflight-fixtures/MutatingFloor/bad-unlisted", "tools/preflight-fixtures/MutatingFloor/bad-missing", "tools/preflight-fixtures/MutatingFloor/bad-unreadable",
             "tools/preflight-fixtures/MutatingFloor/bad-parens"],
            ["tools/preflight-fixtures/AuthSuite/good", "tools/preflight-fixtures/GatewayOnly/good", "tools/preflight-fixtures/MutatingFloor/good"],
            ["tools/preflight-fixtures/AuthSuite/empty", "tools/preflight-fixtures/GatewayOnly/empty", "tools/preflight-fixtures/MutatingFloor/empty"]) with { Plan = EventSpawns },
        C("D25", "RollbackDrill", "rollback-drill.ps1 -SelfTest (pairs and fixtures under tools/rollback-drill-fixtures)",
            ["tools/rollback-drill-fixtures/bad", "tools/rollback-drill-fixtures/pair-other", "tools/rollback-drill-fixtures/pair-otherkey",
             "tools/rollback-drill-fixtures/pair-otherlocation"],
            ["tools/rollback-drill-fixtures/good", "tools/rollback-drill-fixtures/pair-empower", "tools/rollback-drill-fixtures/pair-modifiers",
             "tools/rollback-drill-fixtures/pair-chance", "tools/rollback-drill-fixtures/pair-aroundplayer"],
            ["tools/rollback-drill-fixtures/empty"]) with { Plan = EventSpawns },
        C("D26", "Release", "preflight › Test-CheckReleaseTags and Test-CheckVersion, then release-verify.ps1 -SelfTest",
            ["tools/preflight-fixtures/ReleaseTags/bad", "tools/preflight-fixtures/ReleaseTags/bad-2", "tools/preflight-fixtures/Version/bad",
             "selftest missing asset", "selftest differing hash"],
            ["tools/preflight-fixtures/ReleaseTags/good", "tools/preflight-fixtures/Version/good", "selftest matching hash"],
            ["tools/preflight-fixtures/ReleaseTags/empty", "tools/preflight-fixtures/Version/empty", "selftest no audit records the asset"]) with { Plan = EventSpawns },
        C("D27", "Records", "preflight -AuditOf, -SessionsOf and -Paths -DeclaredOf › AuditSteps, SessionLogs, Paths and DataInventory",
            ["tools/preflight-fixtures/AuditSteps/bad", "tools/preflight-fixtures/AuditSteps/bad-2", "tools/preflight-fixtures/SessionLogs/bad", "tools/preflight-fixtures/SessionLogs/bad-2",
             "tools/preflight-fixtures/SessionLogs/bad-uncounted", "tools/preflight-fixtures/SessionLogs/bad-uncounted-2",
             "tools/preflight-fixtures/SessionLogs/bad-uncounted-3", "tools/preflight-fixtures/SessionLogs/bad-uncounted-4",
             "tools/preflight-fixtures/SessionLogs/bad-uncounted-5",
             "tools/preflight-fixtures/Paths/bad-undeclared", "tools/preflight-fixtures/Paths/bad-temp", "tools/preflight-fixtures/Paths/bad-tempvar",
             "tools/preflight-fixtures/Paths/bad-datatests", "tools/preflight-fixtures/Paths/bad-datatests-floor", "tools/preflight-fixtures/DataInventory/bad", "tools/preflight-fixtures/DataInventory/bad-2"],
            ["tools/preflight-fixtures/AuditSteps/good", "tools/preflight-fixtures/SessionLogs/good", "tools/preflight-fixtures/Paths/good",
             "tools/preflight-fixtures/Paths/good-datatests", "tools/preflight-fixtures/DataInventory/good"],
            ["tools/preflight-fixtures/AuditSteps/empty", "tools/preflight-fixtures/SessionLogs/empty", "tools/preflight-fixtures/Paths/empty",
             "tools/preflight-fixtures/Paths/empty-datatests", "tools/preflight-fixtures/DataInventory/empty"]) with { Plan = EventSpawns },
        C("D31", "Secrets", "preflight › Test-CheckSecrets",
            ["tools/preflight-fixtures/Secrets/bad", "tools/preflight-fixtures/Secrets/bad-3", "tools/preflight-fixtures/Secrets/bad-envread",
             "tools/preflight-fixtures/Secrets/bad-sentinel-zip", "tools/preflight-fixtures/Secrets/bad-sentinel-dist",
             "tools/preflight-fixtures/Secrets/bad-sentinel-build", "tools/preflight-fixtures/Secrets/bad-sentinel-log"],
            ["tools/preflight-fixtures/Secrets/good", "tools/preflight-fixtures/Secrets/good-sentinel"],
            ["tools/preflight-fixtures/Secrets/empty", "tools/preflight-fixtures/Secrets/empty-sentinel"]) with { Plan = EventSpawns },
        C("D34", "EntityWrites", "preflight › Test-CheckEntityWrites",
            ["tools/preflight-fixtures/EntityWrites/bad", "tools/preflight-fixtures/EntityWrites/bad-new", "tools/preflight-fixtures/EntityWrites/bad-unmarked",
             "tools/preflight-fixtures/EntityWrites/bad-em", "tools/preflight-fixtures/EntityWrites/bad-split", "tools/preflight-fixtures/EntityWrites/bad-refrw",
             "tools/preflight-fixtures/EntityWrites/bad-ecb", "tools/preflight-fixtures/EntityWrites/bad-lookup", "tools/preflight-fixtures/EntityWrites/bad-unsafe",
             "tools/preflight-fixtures/EntityWrites/bad-logicusing", "tools/preflight-fixtures/EntityWrites/bad-privatehelper",
             "tools/preflight-fixtures/EntityWrites/bad-destroyutility"],
            ["tools/preflight-fixtures/EntityWrites/good"], ["tools/preflight-fixtures/EntityWrites/empty"]) with { Plan = EventSpawns },

        // ---- automation
        T("D1", "IntervalTrigger", "EventValidationTests", ["value_missing_or_out_of_range", "min_above_max", "unknown_key"], ["bounds_and_scope"],
            ["trigger_without_values"]) with { Plan = Automation },
        T("D2", "IntervalClock", "AutomationTests",
            ["active_keeps_next", "absent_next_fires", "due_fires_twice", "next_beyond_max_kept", "load_keeps_removed_or_non_interval",
             "load_keeps_next_at_or_before_boot"],
            ["draw_within_range", "tick_prunes_and_fires"], ["no_definition"]) with { Plan = Automation },
        T("D4", "FanOutKey", "EventValidationTests", ["location_not_aroundplayer", "value_bad"], ["valid_fanout"], ["fanout_object"]) with { Plan = Automation },
        T("D18", "AutomationTemplates", "TemplateLibraryTests", ["a_field_differs"], ["as_planned"], ["none_in_an_empty_catalogue"]) with { Plan = Automation },
        T("D5", "FanOutPick", "AutomationTests", ["picks_closer_than_spacing", "ineligible_or_twice", "more_than_max", "focus_not_first"],
            ["one_centre_equals_choose", "spaced_players_in_scope_only"], ["no_players"]) with { Plan = Automation },
        T("D6", "FanOutCaps", "AutomationTests",
            ["groups_exceed_caps", "deal_not_round_robin", "claimed_skips_another", "no_group_spawns", "skip_reason_not_first_group"],
            ["one_centre_equals_decide", "line_counts_groups_only"], ["no_eligible_player"]) with { Plan = Automation },
        T("D8", "RegionEnteredTrigger", "EventValidationTests", ["scope_missing_or_global", "cooldown_out_of_range", "unknown_key"],
            ["one_region_and_default_cooldown"], ["scope_array"]) with { Plan = Automation },
        T("D9", "RegionEntries", "AutomationTests",
            ["first_sighting_counts", "move_within_or_out_of_scope_counts", "dead_player_enters", "inside_cooldown", "refused_entry_skips_cooldown",
             "relog_resets_cooldown", "rows_exceed_bound", "absent_keeps_row"],
            ["gap_to_scope_is_entry", "respawn_into_scope_is_entry"], ["no_players"]) with { Plan = Automation },
        T("D10", "FactionKillsTrigger", "EventValidationTests", ["factions_bad", "kills_or_window_out_of_range", "shared_or_key_bad"],
            ["bandits_and_bounds"], ["factions_array"]) with { Plan = Automation },
        T("D11", "KillWindows", "AutomationTests",
            ["non_player_or_servant_kill_counts", "our_unit_or_minion_counts", "other_faction_or_out_of_scope", "old_kills_count", "fires_twice",
             "dropped_fire_keeps_counter", "shared_counts_per_player", "bounds_exceeded"],
            ["owner_kill_counts", "router_reaches_startable_only"], ["no_deaths"]) with { Plan = Automation },
        T("D13", "Focus", "AutomationTests", ["eligible_focus_not_first", "ineligible_focus_skips_wave", "other_trigger_carries_focus", "focus_reaches_state_or_line"],
            ["focus_first"], ["no_focus"]) with { Plan = Automation },
        T("D14", "TriggerRules", "AutomationTests",
            ["disabled_definition_fires", "active_event_reaches_conditions", "two_refusals_in_60s_log_twice", "held_count_lost",
             "cooldown_drop_sets_dedupe_key", "dedupe_lets_twice_in_5s"],
            ["one_line_and_held_count"], ["no_trigger"]) with { Plan = Automation },
        T("D15", "PlayerScan", "AutomationDependencyFailureTests", ["throwing_scan_escapes_or_logs_twice", "garbage_position_reaches_a_definition",
            "login_during_a_gap_is_an_entry"],
            ["good_scan_clears_entry_and_next_streak_logs", "refusal_rows_follow_the_definitions"], ["reads_no_player_without_a_definition"])
            with { Plan = Automation },
        T("D15", "KillRead", "AutomationDependencyFailureTests", ["throwing_read_escapes_or_logs_twice", "unavailable_hook_leaves_factionkills_on",
            "garbage_faction_or_position_counts"], ["good_read_clears_entry", "entry_clears_when_no_definition_reads_kills"],
            ["no_death_no_read_no_streak"]) with { Plan = Automation },
        T("D15", "StateWrite", "AutomationDependencyFailureTests", ["failed_flush_drops_the_next"], ["recovered_flush_writes_the_next"],
            ["no_interval_no_key"]) with { Plan = Automation },
        T("D16", "Automation", "CommandArgTests", ["value_out_of_range"], ["values_in_range", "field_maps_to_its_type"], ["value"]) with { Plan = Automation },
        T("D16", "Automation", "AuthoringTests", ["value_refused", "other_trigger_type", "fanout_on_point_or_empower"],
            ["valid_set_changes_file", "info_shows_next_start"], ["value"]) with { Plan = Automation },
        T("D17", "Automation", "ContractDocTests", ["contract_lacks_value", "trigger_renders_as_manual"], ["api_6_and_values"], ["contract"])
            with { Plan = Automation },
        T("D17", "Automation", "PushTests", ["fanned_out_wave_pushes_more_than_once", "wave_action_reports_per_group"], ["one_push_whatever_the_groups"], ["no_group_spawned"])
            with { Plan = Automation },
        T("D19", "Automation", "PrivacyTests", ["a_line_names_the_player", "state_gains_a_per_player_field"], ["no_line_names_or_locates_a_player"],
            ["no_focus"]) with { Plan = Automation },
        C("D20", "Authorization", "preflight -AuthSuite and -SelfTest › Test-CheckGatewayOnly, Test-CheckEntityWrites, Test-CheckMutatingFloor and Test-CheckFaultInjection",
            ["tools/preflight-fixtures/GatewayOnly/bad-tickcaller", "tools/preflight-fixtures/GatewayOnly/bad-new", "tools/preflight-fixtures/EntityWrites/bad",
             "tools/preflight-fixtures/EntityWrites/bad-new", "tools/preflight-fixtures/MutatingFloor/bad", "tools/preflight-fixtures/FaultInjection/bad",
             "tools/preflight-fixtures/FaultInjection/bad-2"],
            ["tools/preflight-fixtures/GatewayOnly/good", "tools/preflight-fixtures/EntityWrites/good", "tools/preflight-fixtures/MutatingFloor/good",
             "tools/preflight-fixtures/FaultInjection/good"],
            ["tools/preflight-fixtures/GatewayOnly/empty", "tools/preflight-fixtures/EntityWrites/empty", "tools/preflight-fixtures/MutatingFloor/empty",
             "tools/preflight-fixtures/FaultInjection/empty"]) with { Plan = Automation },
        T("D27", "ChatBytes", "CommandArgTests", ["automation_line_exceeds_480", "automation_line_holds_markup"], ["automation_lines_at_maximum_lengths"],
            ["automation_fields"]) with { Plan = Automation },
        T("D32", "WalkLine", "SpawnPlacementTests", ["point_behind_a_wall_accepted", "point_across_water_accepted", "point_on_enclosed_island_accepted",
            "shortened_under_min_dist_or_past_its_block", "budget_overspent", "free_answer_reused_in_its_tile", "centre_at_its_origin_unchecked",
            "out_of_scope_line_end_drops_the_line", "unchecked_reason_missing_or_wrong", "slope_refused", "two_level_step_walked",
            "player_off_level_not_found", "player_by_an_edge_not_moved", "bridge_deck_spawns_in_water"], ["open_field_unchanged", "reach_origin_per_location", "planning_split_timed"],
            ["reach_checks_only_the_spot"]) with { Plan = Automation },
        T("D34", "WalkSurvey", "SpawnPlacementTests", ["distance_past_first_failing_sample", "wrong_reason", "budget_overspent",
            "line_holds_a_coordinate", "level_not_followed", "moved_start_not_shown"], ["open_field_clear"], ["no_check"]) with { Plan = Automation },
        C("D28", "DependencySuite", "preflight -DependencySuite automation",
            ["selftest DependencySuite/bad", "selftest DependencySuite/bad-2", "selftest DependencySuite/bad-floor-spawns"], ["selftest DependencySuite/good"],
            ["selftest DependencySuite/empty"]) with { Plan = Automation },
        T("D29", "Phantoms", "AutomationTests", ["value_outside_1_9", "no_eligible_real_player", "unusable_kept", "phantom_reaches_scan_or_hunt"],
            ["four_at_200m_steps"], ["value"]) with { Plan = Automation },
        T("D30", "ControlCases", "ControlCaseTests", ["table_breaks_a_rule", "pending_key_has_a_row", "pending_after_its_post_audit", "pending_at_release"],
            ["plan_and_table_agree"], ["plan_without_controls"]) with { Plan = Automation },
        T("D31", "StateNextInterval", "AutomationTests", ["bad_entry_drops_others", "empty_gains_key"], ["fixture_round_trip"], ["no_key"]) with { Plan = Automation },
        C("D21", "TimingSpan", "preflight -TimingSpan -MinScans › Test-CheckTimingSpan",
            ["tools/preflight-fixtures/TimingSpan/bad-noscans", "tools/preflight-fixtures/TimingSpan/bad-avg", "tools/preflight-fixtures/TimingSpan/bad-slow",
             "tools/preflight-fixtures/TimingSpan/bad-tracked", "tools/preflight-fixtures/TimingSpan/bad-notarget"],
            ["tools/preflight-fixtures/TimingSpan/good"], ["tools/preflight-fixtures/TimingSpan/empty"]) with { Plan = Automation },
        C("D23", "RollbackDrill", "rollback-drill.ps1 -SelfTest (pairs and fixtures under tools/rollback-drill-fixtures)",
            ["tools/rollback-drill-fixtures/pair-othertrigger", "tools/rollback-drill-fixtures/interval-seed/state-without.json"],
            ["tools/rollback-drill-fixtures/pair-interval", "tools/rollback-drill-fixtures/pair-fanout", "tools/rollback-drill-fixtures/interval-seed/state-with.json"],
            ["tools/rollback-drill-fixtures/empty"]) with { Plan = Automation },
        C("D24", "Release", "preflight › Test-CheckReleaseTags and Test-CheckVersion, then release-verify.ps1 -SelfTest",
            ["tools/preflight-fixtures/ReleaseTags/bad", "tools/preflight-fixtures/ReleaseTags/bad-2", "tools/preflight-fixtures/Version/bad",
             "selftest missing asset", "selftest differing hash"],
            ["tools/preflight-fixtures/ReleaseTags/good", "tools/preflight-fixtures/Version/good", "selftest matching hash"],
            ["tools/preflight-fixtures/ReleaseTags/empty", "tools/preflight-fixtures/Version/empty", "selftest no audit records the asset"]) with { Plan = Automation },
        C("D25", "Records", "preflight -AuditOf, -SessionsOf and -Paths -DeclaredOf › AuditSteps, SessionLogs, Paths and DataInventory",
            ["tools/preflight-fixtures/AuditSteps/bad", "tools/preflight-fixtures/AuditSteps/bad-2", "tools/preflight-fixtures/SessionLogs/bad", "tools/preflight-fixtures/SessionLogs/bad-2",
             "tools/preflight-fixtures/SessionLogs/bad-uncounted", "tools/preflight-fixtures/SessionLogs/bad-uncounted-2",
             "tools/preflight-fixtures/SessionLogs/bad-uncounted-3", "tools/preflight-fixtures/SessionLogs/bad-uncounted-4",
             "tools/preflight-fixtures/SessionLogs/bad-uncounted-5",
             "tools/preflight-fixtures/Paths/bad-undeclared", "tools/preflight-fixtures/Paths/bad-temp", "tools/preflight-fixtures/Paths/bad-tempvar",
             "tools/preflight-fixtures/Paths/bad-datatests", "tools/preflight-fixtures/Paths/bad-datatests-floor", "tools/preflight-fixtures/DataInventory/bad", "tools/preflight-fixtures/DataInventory/bad-2"],
            ["tools/preflight-fixtures/AuditSteps/good", "tools/preflight-fixtures/SessionLogs/good", "tools/preflight-fixtures/Paths/good",
             "tools/preflight-fixtures/Paths/good-datatests", "tools/preflight-fixtures/DataInventory/good"],
            ["tools/preflight-fixtures/AuditSteps/empty", "tools/preflight-fixtures/SessionLogs/empty", "tools/preflight-fixtures/Paths/empty",
             "tools/preflight-fixtures/Paths/empty-datatests", "tools/preflight-fixtures/DataInventory/empty"]) with { Plan = Automation },
        C("D26", "Secrets", "preflight › Test-CheckSecrets",
            ["tools/preflight-fixtures/Secrets/bad", "tools/preflight-fixtures/Secrets/bad-3", "tools/preflight-fixtures/Secrets/bad-envread",
             "tools/preflight-fixtures/Secrets/bad-sentinel-zip", "tools/preflight-fixtures/Secrets/bad-sentinel-dist",
             "tools/preflight-fixtures/Secrets/bad-sentinel-build", "tools/preflight-fixtures/Secrets/bad-sentinel-log"],
            ["tools/preflight-fixtures/Secrets/good", "tools/preflight-fixtures/Secrets/good-sentinel"],
            ["tools/preflight-fixtures/Secrets/empty", "tools/preflight-fixtures/Secrets/empty-sentinel"]) with { Plan = Automation },
        // ---- wave-sets
        T("D1", "WaveList", "EventValidationTests", ["a_key_is_out_of_range", "both_forms_load_together"], ["the_bounds_and_counts_its_waves"],
            ["no_waveList_key"]) with { Plan = WaveSets },
        T("D2", "ScoreboardKey", "EventValidationTests", ["not_a_boolean"], ["both_forms_and_defaults_off"], ["key_absent"]) with { Plan = WaveSets },
        T("D3", "EntryTuning", "WaveSetTests", ["two_entries_of_one_prefab_merge", "a_clamp_drops_an_entry_tuning", "the_deal_drops_an_entry_tuning"],
            ["the_chance_roll_with_its_entry", "units_form_one_tuning_per_action"], ["entry_without_modifiers"]) with { Plan = WaveSets },
        T("D4", "Schedule", "WaveSetTests", ["an_earlier_instance_unit_holds_a_wave", "a_blocked_wave_releases_its_successor", "a_wave_due_at_the_end_spawns", "the_units_form_changes"],
            ["the_earlier_of_after_and_cleared", "a_cleared_only_wave_only_after_the_clear", "an_after_only_wave_without_the_clear",
             "a_skipped_wave_cleared_at_its_decision"], ["no_wave_left"]) with { Plan = WaveSets },
        T("D5", "WaveCleared", "SpawnLedgerTests", ["an_earlier_instance_unit_counts", "a_pending_order_or_a_live_unit_remains", "another_event_or_wave_counts", "an_undecided_wave_reads_cleared"],
            ["every_removal_path"], ["no_order_ever"]) with { Plan = WaveSets },
        T("D6", "Readers", "WaveSetTests", ["the_units_form_changes", "a_planted_reader_is_added"],
            ["the_warning_time_of_each_waveList_wave", "only_the_schedule_reading_intervalSeconds"], ["scan_of_no_files"]) with { Plan = WaveSets },
        T("D7", "Victory", "WaveSetTests", ["an_earlier_wave_still_lives", "the_waves_are_not_all_decided", "a_wave_was_not_fought",
            "the_skip_cascade_ends_the_event", "a_units_form_event_ends_early"], ["the_last_wave_cleared"], ["no_active_event"]) with { Plan = WaveSets },
        T("D8", "Counting", "ScoreboardTests", ["the_201st_player_gets_a_row", "rows_outlive_the_event", "a_native_or_another_events_unit_credits",
            "a_familiar_or_summon_kill_is_not_credited", "a_death_to_a_projectile_or_summon_is_not_credited", "an_earlier_instance_unit_credits"],
            ["kills_and_deaths_per_event", "ties_by_fewer_deaths_then_the_earlier_credit", "the_name_at_the_latest_credit"], ["no_credit"]) with { Plan = WaveSets },
        T("D13", "KillRead", "WaveSetDependencyFailureTests", ["a_throwing_read_skips_died_or_a_later_death", "the_entry_outlives_a_good_read",
            "a_read_happens_with_no_scoreboard_event", "an_edit_mid_run_stops_the_counting"], ["a_kill_and_a_death_credited"], ["no_death"]) with { Plan = WaveSets },
        T("D18", "ClearedRead", "WaveSetDependencyFailureTests", ["a_throwing_read_starts_the_wave_or_logs_twice"], ["a_good_read_clears_the_entry"],
            ["no_wave_waits_for_a_clear"]) with { Plan = WaveSets },
        C("D18", "DependencySuite", "preflight -DependencySuite wave-sets",
            ["selftest DependencySuite/bad", "selftest DependencySuite/bad-2", "selftest DependencySuite/bad-floor-spawns"], ["selftest DependencySuite/good"],
            ["selftest DependencySuite/empty"]) with { Plan = WaveSets },
        T("D9", "Admins", "ScoreboardTests", ["an_admin_counts_with_the_key_false"], ["an_admin_with_the_key_true", "the_cfg_default_false"], ["only_admins"])
            with { Plan = WaveSets },
        T("D10", "Lines", "ScoreboardTests", ["a_line_exceeds_480_bytes", "a_fourth_name_appears", "a_name_keeps_markup"], ["the_top_three_and_the_totals"],
            ["no_player_scored"]) with { Plan = WaveSets },
        T("D11", "EndPaths", "WaveSetTests", ["runtime_skips_an_end_path", "a_silent_path_shows", "an_event_without_the_key_shows"], ["the_three_showing_paths"], ["no_player_scored"])
            with { Plan = WaveSets },
        T("D12", "WaveSets", "PrivacyTests", ["a_queued_scoreboard_line_reaches_the_log", "a_name_reaches_a_line", "another_builder_takes_a_player_name", "state_gains_a_property"],
            ["the_name_only_on_the_scoreboard"], ["no_scoreboard_key"]) with { Plan = WaveSets },
        T("D14", "WaveSets", "CommandArgTests", ["a_units_form_field_meets_a_wave_list", "value_out_of_range", "field_not_settable", "a_conversion_takes_another_field", "a_start_key_breaks_a_rule",
            "a_reply_exceeds_480_bytes", "the_table_and_settable_fields_differ"],
            ["values_in_range", "conversion_of_a_units_form_event", "append_and_remove_waves", "a_unit_modifier"], ["value"]) with { Plan = WaveSets },
        T("D15", "WaveSets", "AuthoringTests", ["a_line_exceeds_480_bytes", "the_units_form_info_changes"], ["one_line_per_wave"], ["entry_without_modifiers"])
            with { Plan = WaveSets },
        T("D16", "WaveSets", "TemplateLibraryTests", ["the_template_differs"], ["graveyard_waves_as_planned"], ["none_in_an_empty_catalogue"])
            with { Plan = WaveSets },
        T("D17", "WaveSets", "ContractDocTests", ["contract_lacks_a_sentence", "the_victory_end_sends_more_than_one_push"], ["api_6_and_the_two_sentences"],
            ["contract"]) with { Plan = WaveSets },
        T("D19", "ControlCases", "ControlCaseTests", ["table_breaks_a_rule", "pending_key_has_a_row", "pending_after_its_post_audit", "pending_at_release"],
            ["plan_and_table_agree"], ["plan_without_controls"]) with { Plan = WaveSets },
    ];
}
